needs: []
permanentLimit: 1
spawnFirework: true
endParticle: hugeexplosion
displayName: test
descriptions:
  - '内含奖品:'
  - '[ 233 ] * 1天'
  - '[ 466 ] * 1天'
prizes:
  test1:
    showoriginname: true
    displayitem: 276:0:1:null
    possibility: 20
    description: '233'
    broadcast: true
    items:
      - 1:0:1:null
    consolecommands: []
    rarity: default
  test2:
    showoriginname: true
    displayitem: 1:0:1:null
    possibility: 20
    description: 没有奖励
    broadcast: true
    items: []
    consolecommands: []
    rarity: default
  test3:
    showoriginname: true
    displayitem: 1:0:1:null
    possibility: 20
    description: 没有奖励
    broadcast: true
    items: []
    consolecommands: []
    rarity: default
  test4:
    showoriginname: true
    displayitem: 1:0:1:null
    possibility: 20
    description: 没有奖励
    broadcast: true
    items: []
    consolecommands: []
    rarity: default
  test5:
    showoriginname: true
    displayitem: 1:0:1:null
    possibility: 20
    description: 没有奖励
    broadcast: true
    items: []
    consolecommands: []
    rarity: default
  test6:
    showoriginname: true
    displayitem: 1:0:1:null
    possibility: 20
    description: 没有奖励
    broadcast: true
    items: []
    consolecommands: []
    rarity: default
  test7:
    showoriginname: true
    displayitem: 1:0:1:null
    possibility: 20
    description: 没有奖励
    broadcast: true
    items: []
    consolecommands: []
    rarity: default
  test8:
    showoriginname: true
    displayitem: 1:0:1:null
    possibility: 20
    description: 没有奖励
    broadcast: true
    items: []
    consolecommands: []
    rarity: default
bonuses:
  test1:
    times: 20
    prize: test1
    items:
      - 1:0:1:null
    consolecommands:
      - say test